blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogDeleteView, BlogDetailView,
                        BlogListView, BlogUpdateView)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path('subscription-required/', views.subscription_required, name='subscription_required')
]

"""
URL-шаблоны для управления блогами.

Includes URL patterns for listing, viewing, updating, deleting, and creating blog entries.

URL Patterns:
    '' (str): Список блогов.
    'view/<int:pk>/' (str): Просмотр конкретной статьи блога по идентификатору.
    'update/<int:pk>/' (str): Обновление конкретной статьи блога по идентификатору.
    'delete/<int:pk>/' (str): Удаление конкретной статьи блога по идентификатору.
    'create/' (str): Создание новой статьи блога.

Attributes:
    app_name (str): Имя приложения блога для пространства имен URL.
"""

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("blog.urls", namespace="blog")),
                  path("users/", include(("users.urls", "users"), namespace="users")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileView, SubscriptionCreate, UserRegisterView

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("perform_create/", SubscriptionCreate.as_view(), name="perform_create"),
]

"""
URL-шаблоны для аутентификации пользователя и управления профилем.

- 'login': Отображает страницу входа с использованием LoginView Django и пользовательским шаблоном.
- 'logout': Выходит из системы пользователя с использованием LogoutView Django.
- 'register': Отображает страницу регистрации с использованием UserRegisterView.
- 'profile': Отображает страницу профиля пользователя с использованием ProfileView.
- 'perform_create': Эндпоинт для выполнения операции создания, вероятно, создание объекта.
"""

blog/models.py
from django.conf import settings
from django.db import models

from config.settings import NULLABLE


class Blog(models.Model):
    """
    Модель блога для хранения статей.

    Attributes:
        title (CharField): Заголовок статьи (максимальная длина 100 символов).
        content (TextField): Содержимое статьи.
        preview (ImageField): Изображение предпросмотра статьи (загружается в папку 'preview/').
        count_view (IntegerField): Количество просмотров статьи (по умолчанию 0).
        created_at (DateField): Дата публикации статьи (автоматически добавляется при создании).
        user (ForeignKey): Владелец статьи (ссылка на модель пользователя из настроек Django).
        price (IntegerField, optional): Цена на подписку (может быть пустым).

    Methods:
        __str__: Возвращает строковое представление объекта, используя заголовок статьи.
    """

    title = models.CharField(max_length=100, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержимое статьи")
    preview = models.ImageField(
        upload_to="preview/", verbose_name="Изображение", **NULLABLE
    )
    count_view = models.IntegerField(default=0, verbose_name="Количество просмотров")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата публикации")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Владелец", **NULLABLE
    )
    is_premium = models.BooleanField(default=False, verbose_name="Платный контент")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        permissions = [
            ("can_edit_title", "Can edit title"),
            ("can_edit_content", "Can edit content"),
        ]

blog/forms.py
from django.forms import ModelForm

from blog.models import Blog
from users.forms import StyleFormMixin


class BlogForm(StyleFormMixin, ModelForm):
    """
    Форма для создания и редактирования блога.

    Наследуется от StyleFormMixin для добавления стилевых функций к форме.

    Attributes:
        Meta (class): Вложенный класс для определения метаинформации о форме.
            model (Model): Модель, с которой связана форма (Blog).
            fields (tuple): Поля модели, которые должны быть включены в форму
                (title, content, preview).
    """

    class Meta:
        """
        Метаинформация о форме для модели Blog.
        """

        model = Blog
        fields = ["title", "content", "preview"]


class BlogModeratorForm(StyleFormMixin, ModelForm):
    """
    Форма для создания и редактирования блога.

    Наследуется от StyleFormMixin для добавления стилевых функций к форме.

    Attributes:
        Meta (class): Вложенный класс для определения метаинформации о форме.
            model (Model): Модель, с которой связана форма (Blog).
            fields (tuple): Поля модели, которые должны быть включены в форму
                (title, content, preview).
    """

    class Meta:
        """
        Метаинформация о форме для модели Blog.
        """

        model = Blog
        fields = ["title", "content"]


class BlogFormPremium(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "content", "preview", "is_premium"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from blog.forms import BlogForm, BlogFormPremium
from blog.models import Blog
from users.models import Subscription
from users.services import check_payment_status
from django.core.exceptions import ObjectDoesNotExist


class BlogCreateView(CreateView):
    model = Blog
    template_name = "blog/blog_form.html"
    success_url = reverse_lazy("blog:blog_list")

    def get_context_data(self, **kwargs):
        """
        Получает дополнительные данные контекста для отображения формы создания блога.

        Args:
        **kwargs: Дополнительные аргументы ключевых слов, передаваемые в метод.

        Returns:
        dict: Словарь с дополнительными данными контекста для шаблона.
            Включает в себя заголовок страницы для создания блога.
        """
        context = super().get_context_data(**kwargs)
        context["title"] = "Создание блога"
        return context

    def form_valid(self, form):
        """
        Метод при успешном создании.
        Если пользователь авторизован -
        Добавляет текущего пользователя при создании объекта.
        Меняет флаг публикации на положительный и определяет платный контент.
        """
        new_content = form.save(commit=False)
        if self.request.user.is_authenticated:
            new_content.owner = self.request.user  # Используйте 'owner' вместо 'user'
            new_content.publish = True
            # Устанавливаем флаг платного контента в зависимости от статуса пользователя
            new_content.is_premium = self.request.user.payments.exists() is not None or self.request.user.is_superuser
        new_content.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        try:
            subscription = Subscription.objects.get(pk=user.payments_id)
            if check_payment_status(subscription.content_id):
                return BlogFormPremium
            else:
                return BlogForm
        except ObjectDoesNotExist:
            return BlogForm


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ("title", "content", "preview")
    success_url = reverse_lazy("blog:blog_list")

    def get_object(self, queryset=None):
        """
        Получает объект товара из базы данных и проверяет, является ли текущий пользователь владельцем товара.
        """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_superuser:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object


class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"

    def get_queryset(self):
        """
            Возвращает queryset блог-постов в зависимости от аутентификации пользователя и его прав.

            Если пользователь не аутентифицирован, возвращается queryset блог-постов,
            которые не являются премиумными.

            Если пользователь является суперпользователем или аутентифицирован, возвращается полный queryset
            всех блог-постов.

            Возвращает:
            - QuerySet: В зависимости от статуса аутентификации и прав пользователя,
              возвращается соответствующий QuerySet блог-постов.
        """
        if not self.request.user.is_authenticated:
            return Blog.objects.filter(is_premium=False)
        elif self.request.user.is_superuser or self.request.user.is_authenticated or check_payment_status(
                self.request.user.payments.content_id):
            return Blog.objects.all()


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """
            Возвращает объект блога для текущей страницы и обновляет счетчик просмотров.

            Args:
            - queryset (QuerySet, optional): QuerySet для поиска объекта блога.

            Returns:
            - Blog: Обновленный объект блога.
        """
        self.object = super().get_object(queryset)
        self.object.count_view += 1
        self.object.save()
        return self.object

    def get_queryset(self):
        """
            Возвращает queryset блог-постов в зависимости от аутентификации пользователя и его прав.

            Если пользователь не аутентифицирован, возвращается queryset блог-постов,
            которые не являются премиумными.

            Если пользователь является суперпользователем или аутентифицирован, возвращается полный queryset
            всех блог-постов.

            Возвращает:
            - QuerySet: В зависимости от статуса аутентификации и прав пользователя,
            возвращается соответствующий QuerySet блог-постов.
        """
        if not self.request.user.is_authenticated:
            return Blog.objects.filter(is_premium=False)
        elif self.request.user.is_superuser or self.request.user.payments or self.request.user.is_authenticated:
            return Blog.objects.all()


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

    def get_queryset(self):
        """
            Возвращает queryset блог-постов в зависимости от аутентификации пользователя и его прав.

            Если пользователь не аутентифицирован, возвращается queryset блог-постов,
            которые не являются премиумными.

            Если пользователь является суперпользователем или аутентифицирован, возвращается полный queryset
            всех блог-постов.

            Возвращает:
            - QuerySet: В зависимости от статуса аутентификации и прав пользователя,
            возвращается соответствующий QuerySet блог-постов.
        """
        if not self.request.user.is_authenticated:
            return Blog.objects.filter(is_premium=False)
        elif self.request.user.is_superuser or self.request.user.payments or self.request.user.is_authenticated:
            return Blog.objects.all()

    def test_func(self):
        blog = self.get_object()
        return self.request.user == blog.owner or self.request.user.is_superuser


def subscription_required(request):
    return render(request, 'blog/blog_not_available.html')

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Album example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О нас</h4>
                    <p class="text-muted">Добро пожаловать на You100gramm!</p>

                    <p class="text-muted">YouBlog – это ваше пространство для выражения мыслей, обмена идеями и общения с
                        единомышленниками. Мы создали эту платформу, чтобы предоставить вам возможность делиться своими
                        увлечениями, опытом и знаниями с миром.</p>
                </div>
                {% block menu %}

                {% include 'blog/includes/inc_menu.html' %}

                {% endblock %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'blog:blog_list' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>You100gramm</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">You100gramm</h1>
            <p class="lead text-muted">You100gramm - делитесь своими историями, вдохновляйте мир!</p>
        </div>
    </section>
    {% block content %}
    {% endblock %}
</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y' %}</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6 col-lg-4">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Удаление блога</h4>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'blog:blog_delete' object.pk %}" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Хотите удалить блог - <strong>{{ object.title }}</strong>?</p>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-sm btn-outline-danger">Удалить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-sm btn-outline-secondary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load tag %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                        <img class="good_logo" src="{{ blog.preview|mymedia }}" alt="Фото" style="width:100%;">
                        <h1 class="card-title">{{ blog.title }}</h1>
                        <p class="card-text">{{ blog.content }}</p>
                        <p class="card-text"><small class="text-muted">Количество просмотров: {{ blog.count_view }}</small></p>
                        <p class="card-text"><small class="text-muted">Дата публикации: {{ blog.created_at }}</small></p>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-sm btn-outline-secondary mt-3">Вернуться назад к списку новостей</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% if object %}
        <h1 class="display-4">Редактировать блог</h1>
    {% else %}
        <h1 class="display-4">Добавить блог</h1>
    {% endif %}
</div>

<div class="row justify-content-center">
    <div class="col-md-6 col-lg-4">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">
                    {% if object %}
                        Редактирование блога
                    {% else %}
                        Создание блога
                    {% endif %}
                </h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-sm btn-outline-primary">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'blog:blog_list' %}" class="w-100 btn btn-sm btn-outline-secondary">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load tag %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="{{ object.preview|mymedia }}" alt="{{ object.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text">Владелец: {{ object.owner }}</p>
                        <p class="card-text">Подписка: {{ object.is_premium }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if not object.is_premium or user.payments or user == object.owner and user.is_authenticated or user.is_superuser %}
                                <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-sm btn-outline-primary">Подробнее</a>
                                {% else %}
                                <a href="{% url 'blog:subscription_required' %}" class="btn btn-sm btn-outline-danger">Платный контент</a>
                                {% endif %}
                                {% if user == object.owner or user.is_superuser %}
                                <a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-sm btn-outline-danger">Удалить</a>
                                {% endif %}
                            </div>
                            <small class="text-muted">Опубликовано {% now "H:i" %}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_not_available.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title">Этот пост доступен только подписчикам</h1>
                        <p class="card-text">Для доступа к этому контенту, пожалуйста, оформите подписку.</p>
                        <a href="{% url 'users:perform_create' %}" class="btn btn-primary">Оформить подписку</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}